import React from 'react';
import { X, Bell, CheckCircle2, AlertTriangle, Info, Trash2 } from 'lucide-react';
import { NotificationItem } from '../types';

interface NotificationDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  notifications: NotificationItem[];
  onMarkAllRead: () => void;
  onClearAll: () => void;
}

export const NotificationDrawer: React.FC<NotificationDrawerProps> = ({
  isOpen,
  onClose,
  notifications,
  onMarkAllRead,
  onClearAll
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex justify-end animate-in fade-in duration-200">
      {/* Backdrop */}
      <div 
        onClick={onClose}
        className="fixed inset-0 bg-black/60 backdrop-blur-sm transition-opacity" 
      />

      {/* Drawer Panel */}
      <div className="relative w-full max-w-md bg-[#070913] border-l border-white/10 h-full p-6 shadow-2xl flex flex-col justify-between z-10 animate-in slide-in-from-right duration-300">
        
        {/* Header */}
        <div>
          <div className="flex items-center justify-between pb-4 border-b border-white/10 mb-4">
            <div className="flex items-center gap-2">
              <Bell className="w-5 h-5 text-indigo-400" />
              <h3 className="text-base font-bold text-white font-display">Intelligence Alerts</h3>
            </div>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/5"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <div className="flex items-center justify-between text-xs mb-4">
            <span className="text-slate-400">{notifications.length} Total Alerts</span>
            <div className="flex gap-2">
              <button 
                onClick={onMarkAllRead}
                className="text-cyan-400 hover:underline text-[11px]"
              >
                Mark all read
              </button>
              <span className="text-slate-600">•</span>
              <button 
                onClick={onClearAll}
                className="text-rose-400 hover:underline text-[11px]"
              >
                Clear all
              </button>
            </div>
          </div>

          {/* Notifications List */}
          <div className="space-y-3 overflow-y-auto max-h-[calc(100vh-200px)] pr-1">
            {notifications.map((n) => (
              <div
                key={n.id}
                className={`p-3.5 rounded-2xl border transition-all ${
                  n.read 
                    ? 'bg-slate-900/40 border-white/5 opacity-70' 
                    : 'bg-slate-900/80 border-indigo-500/30 shadow-md'
                }`}
              >
                <div className="flex items-start gap-3">
                  <div className="mt-0.5">
                    {n.type === 'alert' ? (
                      <AlertTriangle className="w-4 h-4 text-rose-400" />
                    ) : n.type === 'success' ? (
                      <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    ) : (
                      <Info className="w-4 h-4 text-cyan-400" />
                    )}
                  </div>
                  <div className="flex-1 space-y-1">
                    <div className="flex justify-between items-baseline">
                      <h4 className="text-xs font-bold text-white">{n.title}</h4>
                      <span className="text-[10px] text-slate-500 font-mono">{n.timestamp}</span>
                    </div>
                    <p className="text-xs text-slate-400 leading-relaxed">{n.description}</p>
                  </div>
                </div>
              </div>
            ))}

            {notifications.length === 0 && (
              <div className="text-center py-12 text-slate-500 text-xs">
                No active notifications. You are fully up to date!
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="pt-4 border-t border-white/10 text-center">
          <p className="text-[11px] text-slate-500">
            Real-time triggers generated by CareerAI neural heuristics.
          </p>
        </div>

      </div>
    </div>
  );
};
